export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  content: string
}

export const posts: BlogPost[] = [
  {
    slug: "why-your-contractor-website-isnt-getting-calls",
    title: "Why Your Contractor Website Isn't Getting You Calls",
    excerpt: "You paid for a website. It looks decent. But the phone isn't ringing. Here's what's actually going wrong.",
    category: "Web Design",
    date: "July 14, 2026",
    content: `<p>You spent money on a website. Maybe a few thousand. Maybe you got your nephew to do it. Either way, it exists. It's out there on the internet. And it's doing absolutely nothing for you.</p><p>Sound familiar? You're not alone. Most contractor websites in Atlantic Canada are basically digital business cards collecting dust. They look fine. Maybe even good. But they don't generate leads because they weren't built to.</p><h2>The real problem isn't how it looks</h2><p>Most web designers focus on making things pretty. That's great for their portfolio but useless for your bottom line. A website that looks like a magazine ad but doesn't show up on Google is like a billboard in the woods. Nobody's seeing it.</p><p>The contractors who are getting 10, 15, 20 calls a week from their website? Their sites aren't necessarily prettier than yours. They're just built differently.</p><h2>What actually gets the phone ringing</h2><p>There are three things that matter more than design:</p><ul><li><strong>Speed.</strong> If your site takes more than 3 seconds to load on a phone, half your visitors leave before they even see your name. Most contractor sites are bloated WordPress themes running on cheap hosting. They're slow and people bounce.</li><li><strong>Clear calls to action.</strong> When someone lands on your site, can they call you in one tap? Is there a form above the fold? Or do they have to scroll through your company history and mission statement first? Nobody cares about your mission statement. They have a leaky roof.</li><li><strong>Google visibility.</strong> If you're not on page one for "[your service] [your city]" then you might as well not have a site at all. 75% of people never click past the first page of Google.</li></ul><h2>The fix isn't another redesign</h2><p>You don't need to throw everything out and start over. Sometimes you do. But usually the bones are fine and you just need someone to rebuild it with search engines and conversions in mind.</p><p>That means proper title tags. Fast loading speeds. A mobile experience that doesn't require pinching and zooming. And content that tells Google exactly what you do and where you do it.</p><p>Your competitor with the ugly website that ranks above you? They figured this out. Or someone figured it out for them. That's the difference.</p>`,
  },
  {
    slug: "google-maps-ranking-atlantic-canada",
    title: "How to Get Into the Google Maps 3-Pack in Atlantic Canada",
    excerpt: "The top 3 spots on Google Maps get almost all the clicks. Here's how local businesses can actually get there.",
    category: "Local SEO",
    date: "July 12, 2026",
    content: `<p>When someone searches "plumber near me" or "roofer Halifax," Google shows a map with three businesses. That's it. Three. Everyone else gets buried below.</p><p>Those three spots get roughly 44% of all the clicks on the page. If you're not in that box, you're fighting over scraps.</p><p>The good news? In Atlantic Canada, the competition for these spots is laughably low compared to Toronto or Vancouver. Most of your competitors haven't done anything to optimize their Google presence. Which means you can win this without spending years on it.</p><h2>What Google actually looks at</h2><p>Google decides who goes in the Map Pack based on three things:</p><ol><li><strong>Relevance.</strong> Does your business profile match what the person searched for? If someone searches "emergency plumber" and your profile just says "plumbing services," you're at a disadvantage.</li><li><strong>Distance.</strong> How close is your business to the person searching? You can't control this one, but you can influence it by setting your service areas properly.</li><li><strong>Prominence.</strong> How well known and trusted is your business online? This comes from reviews, backlinks, citations, and how active your profile is.</li></ol><h2>The stuff you can do this week</h2><p>First, claim and fully complete your Google Business Profile if you haven't already. Every single field. Business hours, services, description, photos. Google gives preference to complete profiles.</p><p>Second, pick your primary category carefully. "Roofing Contractor" is not the same as "Roofing Service." Look at what the top 3 in your area are using and match it.</p><p>Third, start getting reviews. Not fake ones. Real ones from real customers. Ask after every job. Make it easy. Text them a direct link. The businesses in the Map Pack almost always have more reviews than the ones below them.</p><h2>The stuff that takes longer but wins</h2><p>Post on your Google Business Profile weekly. Updates, photos from job sites, offers. Google sees this activity and rewards it.</p><p>Get listed on local directories. YellowPages.ca, BBB, your local chamber of commerce. These are called citations and they tell Google you're a real, established business.</p><p>Build some backlinks. Get mentioned on a local news site or sponsor a community event that links back to your site. One quality local backlink is worth more than 50 random ones from overseas.</p><p>None of this is rocket science. It's just work. And since most of your competitors aren't doing any of it, a little effort goes a long way here in Atlantic Canada.</p>`,
  },
  {
    slug: "what-is-ai-search-optimization",
    title: "What Is AI Search Optimization and Why Should You Care?",
    excerpt: "People are asking ChatGPT for recommendations now. If your business isn't showing up in those answers, you're invisible to a growing chunk of customers.",
    category: "AI Search",
    date: "July 10, 2026",
    content: `<p>Here's something that would have sounded crazy two years ago: people are asking AI chatbots who the best contractor in their area is. And the AI answers them. With specific business names.</p><p>This isn't some future thing. It's happening right now. ChatGPT, Google's Gemini, Perplexity, Claude. Millions of people use these tools daily to find local services. "Who's the best roofer in Moncton?" "Find me a reliable electrician near Dartmouth." Real queries, real answers.</p><p>The question is whether your business is part of those answers or not.</p><h2>How AI decides who to recommend</h2><p>AI assistants don't pull recommendations out of thin air. They look at what's available on the internet about your business. Reviews, your website content, mentions on other sites, your Google Business Profile, directory listings.</p><p>If you have a well-structured website with clear information about what you do and where you do it, lots of positive reviews, and mentions across the web, AI tools are more likely to include you in their answers.</p><p>If your online presence is thin or scattered, you're invisible to these systems.</p><h2>This is different from regular SEO</h2><p>Traditional SEO gets you ranked on Google's search results page. That still matters a lot. But AI search optimization is about being recommended by conversational AI tools.</p><p>The overlap is big. A lot of what helps you rank on Google also helps AI tools find you. But there are specific things you can do to increase your chances of being recommended in AI answers.</p><p>Structuring your content as clear questions and answers helps. Having specific, detailed service pages for each thing you do and each area you serve helps. Being mentioned positively on review sites and forums helps.</p><h2>Why this matters more in smaller markets</h2><p>In Atlantic Canada, almost nobody is thinking about this yet. Which means the window to become the business AI tools recommend is wide open. If you start now, by the time your competitors catch on, you'll be the established answer.</p><p>Think about it. When ChatGPT tells someone "The top-rated roofer in Halifax based on reviews and reputation is [your business]" that's essentially a free referral from the most trusted source your customer has. No ad spend. No bidding on keywords. Just being the obvious answer.</p><p>That's what AI search optimization is about. Becoming the obvious answer.</p>`,
  },
  {
    slug: "how-much-should-a-contractor-website-cost",
    title: "How Much Should a Contractor Website Actually Cost?",
    excerpt: "There's a massive range out there. $500 to $50,000. Here's what you should actually expect to pay and what you get at each level.",
    category: "Web Design",
    date: "July 8, 2026",
    content: `<p>This is the question everyone asks but nobody gives a straight answer to. So here it is.</p><p>If you're a contractor or local service business in Atlantic Canada, a website that actually generates leads will cost you somewhere between $3,000 and $10,000. That's the honest range for a custom site built to perform.</p><p>Can you get something cheaper? Sure. Will it work? Probably not the way you want it to.</p><h2>The $500 to $1,500 range</h2><p>This gets you a template. Someone picks a WordPress theme, swaps in your logo and photos, and calls it done. It'll exist on the internet. It might even look okay. But it won't be optimized for search, it'll probably be slow, and it won't be built to convert visitors into calls.</p><p>For some businesses this is fine as a starting point. If you just need something out there while you get going, no shame in it. But don't expect it to generate business on its own.</p><h2>The $3,000 to $5,000 range</h2><p>This is where you start getting something real. A custom design built around your brand. Proper on-page SEO. Fast loading speeds. Mobile-first approach. Clear calls to action. Maybe 5 to 8 pages covering your services and service areas.</p><p>At this level, the person building it should be thinking about conversions and search from day one. Not just making it look nice. If they're not talking about keywords, page speed, and calls to action during the process, they're just making art.</p><h2>The $5,000 to $10,000 range</h2><p>Now you're talking about a complete system. Website plus SEO setup. Service area landing pages for each city you work in. Google Business Profile optimization. Maybe some initial backlink building. A site that's ready to rank from the moment it launches.</p><p>This is typically what businesses that are serious about growth invest in. Not because expensive equals better, but because doing it right takes time and expertise.</p><h2>What about monthly costs?</h2><p>The website itself is a one-time build. But SEO, content, and ongoing optimization are monthly investments. Budget $800 to $2,000 per month if you want someone actively working on getting you more visibility every single month.</p><p>Think of the website as the engine. Monthly SEO is the fuel. Without fuel, the engine just sits there.</p><h2>The real question to ask</h2><p>Don't ask "how much does a website cost?" Ask "how many calls per month will this generate and what's each call worth to me?"</p><p>If one new customer is worth $5,000 to your business, and a proper website brings you 5 new customers a month, that's $25,000 in monthly revenue from a $5,000 investment. That's not a cost. That's the best ROI in your business.</p>`,
  },
  {
    slug: "local-seo-vs-paid-ads-contractors",
    title: "Local SEO vs. Google Ads: Which One Should Contractors Pick?",
    excerpt: "Both put you in front of customers. But they work completely differently. Here's when to use each one.",
    category: "Local SEO",
    date: "July 6, 2026",
    content: `<p>Contractors ask this all the time. Should I do SEO or just run Google Ads? The answer depends on how fast you need results and how much you hate writing checks to Google every month.</p><h2>How Google Ads works for contractors</h2><p>You pay Google every time someone clicks your ad. For contractors in Atlantic Canada, you're looking at $5 to $30 per click depending on your trade. Plumbers and roofers tend to be on the higher end. Landscapers a bit lower.</p><p>The upside: instant traffic. You turn it on today, you get clicks today. If your site converts well, you get calls today.</p><p>The downside: the moment you stop paying, you disappear. There's no equity building. No compounding effect. It's a faucet. Money in, leads out. Stop the money, the leads stop.</p><p>Also, click fraud is a real thing. Competitors clicking your ads. Bots clicking your ads. Google tries to filter it but it's not perfect. You're paying for some clicks that will never turn into anything.</p><h2>How local SEO works for contractors</h2><p>You invest time and money into making your business show up organically. Google Maps, regular search results, AI answers. Nobody clicks, you don't pay.</p><p>The upside: compounding returns. Every month of work builds on the last. After 6 months of consistent SEO, you're getting calls from work you did months ago. It snowballs. And you don't pay per click.</p><p>The downside: it takes time. You won't rank overnight. Expect 30 to 90 days before you see meaningful movement. For competitive terms, maybe 6 months.</p><h2>So which one?</h2><p>If you need calls right now because you're slow and need revenue immediately, run ads. Use them as a bridge.</p><p>But start SEO at the same time. Build that organic presence so that in 3 to 6 months, you're getting free leads that don't cost you $15 per click. Then you can scale back the ads or turn them off entirely.</p><p>The best contractors we work with use ads to fill gaps and SEO for long-term growth. They don't pick one. They use both strategically.</p><p>But if you can only afford one? SEO. Every time. Because the leads you get in month 8 don't cost you anything extra. With ads, month 8 costs exactly as much as month 1.</p>`,
  },
  {
    slug: "google-business-profile-mistakes",
    title: "7 Google Business Profile Mistakes Killing Your Local Visibility",
    excerpt: "Your GBP is probably half-finished and holding you back. These are the most common mistakes we see with local businesses.",
    category: "Local SEO",
    date: "July 4, 2026",
    content: `<p>Your Google Business Profile is free. It's also one of the most powerful tools for getting local customers. And most businesses are barely using it. Here are the mistakes we see constantly.</p><h2>1. Incomplete profile</h2><p>Google explicitly says complete profiles are more likely to appear in local results. Yet we see businesses with no hours listed, no service descriptions, no photos, no website link. It takes 20 minutes to fill this out completely. Just do it.</p><h2>2. Wrong primary category</h2><p>Your primary category is the single biggest ranking factor for Maps. If you're a roofer and your category says "General Contractor," you're handicapping yourself for every roofing search. Look at what the businesses currently in the Map Pack are using. Copy them.</p><h2>3. No photos or only stock photos</h2><p>Businesses with photos get 42% more requests for directions and 35% more clicks to their website. That's Google's own data. Post real photos from your job sites. Before and after shots. Your team. Your trucks. Real stuff, not stock images of a handshake.</p><h2>4. Not responding to reviews</h2><p>Every review deserves a response. Good ones, bad ones, all of them. Google sees this engagement as a signal that you're an active, caring business. It also shows potential customers that you actually read feedback. Takes 30 seconds per review.</p><h2>5. Ignoring the posts feature</h2><p>Google Business Profile has a posting feature. Think of it like social media for Google. Post weekly updates, photos from recent jobs, seasonal offers. Businesses that post regularly tend to rank better. And it takes five minutes.</p><h2>6. Inconsistent name and address</h2><p>If your business is "Smith Roofing Ltd" on Google but "Smith Roofing" on your website and "Smith's Roofing Services" on YellowPages, Google gets confused. Pick one name. Use it everywhere. Exactly the same. Every character.</p><h2>7. Not asking for reviews</h2><p>Most happy customers would leave a review if asked. They just don't think about it. The businesses with 80+ reviews didn't get there by accident. They asked. After every job. Consistently. Make it dead simple with a direct link or QR code on your invoice.</p><p>Fix these seven things and you're ahead of 80% of local businesses. None of this costs money. Just attention and consistency.</p>`,
  },
  {
    slug: "why-fast-websites-get-more-customers",
    title: "Why a Fast Website Gets You More Customers",
    excerpt: "Every second your site takes to load, you lose visitors. Here's what the data actually says and how to fix it.",
    category: "Web Design",
    date: "July 2, 2026",
    content: `<p>Here's a stat that should bother you: 53% of mobile visitors leave a page that takes longer than 3 seconds to load. More than half. Gone before they even see what you do.</p><p>Now think about your website. Pull it up on your phone right now. Count the seconds. If you see a blank screen or a loading spinner for more than 2 or 3 seconds, you're hemorrhaging potential customers.</p><h2>Why most contractor sites are slow</h2><p>The usual culprits:</p><ul><li>Cheap shared hosting that can't handle traffic</li><li>Unoptimized images. That 4MB photo from your job site looks great but it's murdering your load time</li><li>Bloated WordPress themes with 40 plugins running in the background</li><li>No caching set up</li><li>Scripts and widgets that load before your actual content appears</li></ul><p>You might not notice any of this on your office desktop with fast wifi. But your customers are on their phones, probably on LTE, looking for someone to fix their problem right now. They don't wait.</p><h2>What Google thinks about speed</h2><p>Google has been using page speed as a ranking factor since 2018. In 2021 they rolled out Core Web Vitals, which are basically a speed and user experience scorecard. Slow sites get pushed down in search results. Fast sites get rewarded.</p><p>So not only are you losing visitors who land on your site, you're also getting fewer visitors in the first place because Google ranks you lower. Double hit.</p><h2>What fast actually means</h2><p>Aim for a Largest Contentful Paint under 2.5 seconds. That's the metric Google cares about most. It measures how long it takes for the main content to appear on screen.</p><p>You can test your site at pagespeed.web.dev for free. It'll tell you exactly what's slowing you down and how to fix it.</p><h2>The fix</h2><p>Modern frameworks load faster than traditional WordPress because they serve pre-built pages instead of building them on every visit. Proper image compression and modern formats like WebP cut file sizes by 70%. Good hosting matters. CDNs matter.</p><p>This isn't vanity optimization. Every 100 milliseconds of improvement means roughly 1% more conversions. On a site getting 1,000 visitors a month, that's the difference between 30 calls and 40 calls. Real money.</p>`,
  },
  {
    slug: "reviews-are-your-best-marketing",
    title: "Online Reviews Are the Best Marketing You're Not Doing Enough Of",
    excerpt: "88% of people trust online reviews as much as personal recommendations. If you have 6 reviews, you're losing to someone with 60.",
    category: "Local SEO",
    date: "June 30, 2026",
    content: `<p>Let's say two roofers show up in your Google search. One has 12 reviews with a 4.3 rating. The other has 87 reviews with a 4.8 rating. Who are you calling first?</p><p>Exactly. Everyone picks the one with more reviews. Every single time.</p><p>Reviews are the most underused growth tool for contractors. You do great work every day. Your customers are happy. But unless that satisfaction is publicly visible on Google, it doesn't help you get the next customer.</p><h2>Why reviews matter so much</h2><p>Three reasons:</p><ol><li><strong>Social proof.</strong> People trust other people. 88% of consumers trust online reviews as much as a recommendation from a friend. That's not a made up number. That's real research.</li><li><strong>Google rankings.</strong> Review quantity, frequency, and quality are all ranking factors. Businesses with more reviews rank higher in the Map Pack. Google confirmed this.</li><li><strong>AI recommendations.</strong> When AI tools are deciding who to recommend, they heavily weight review sentiment and volume. More positive reviews means more AI referrals.</li></ol><h2>How to actually get reviews consistently</h2><p>The number one reason businesses don't have enough reviews is they don't ask. That's it. Not some complicated marketing problem. They just don't ask.</p><p>Here's what works:</p><ul><li>Send a text message the day after completing a job with a direct link to your Google review page</li><li>Put a QR code on your invoices that goes directly to your review page</li><li>Ask in person when the customer is clearly satisfied</li><li>Make it easy. The fewer taps required, the more people will actually do it</li></ul><h2>Handling bad reviews</h2><p>They happen. Don't panic. Don't argue. Respond professionally, acknowledge the issue, offer to make it right. Potential customers reading that response see a business that takes responsibility. That's actually a good look.</p><p>One bad review among 50 good ones won't hurt you. But 3 bad reviews among 8 total looks terrible. The solution is volume. Keep asking happy customers until the occasional negative one is a tiny blip.</p>`,
  },
  {
    slug: "what-are-backlinks-and-why-do-they-matter",
    title: "What Are Backlinks and Why Do They Matter for Your Business?",
    excerpt: "Backlinks are other websites linking to yours. They're one of the top 3 ranking factors on Google.",
    category: "Local SEO",
    date: "June 28, 2026",
    content: `<p>Think of a backlink as a vote of confidence. When another website links to yours, Google sees it as a signal that your site is trustworthy and worth showing to people.</p><p>The more quality votes you have, the higher you rank. It's been this way since Google started. And despite everything else changing, backlinks are still one of the top 3 factors Google uses to decide who ranks where.</p><h2>Not all backlinks are equal</h2><p>A link from the CBC is worth more than a link from some random blog nobody reads. Google weighs the authority of the site linking to you. One link from a trusted local news site can move the needle more than 20 links from low-quality directories.</p><p>What matters:</p><ul><li>The authority of the site linking to you</li><li>Whether the link is relevant to your business</li><li>Whether it's a "followed" link</li><li>The context around the link</li></ul><h2>How local businesses get backlinks</h2><p>You're not going to get featured in the New York Times. That's fine. Local backlinks from relevant sites are exactly what you need. Here's how:</p><ul><li><strong>Sponsor local events or teams.</strong> Most event pages and sports leagues link to their sponsors. That's a free, natural backlink from a local site.</li><li><strong>Get listed in local business directories.</strong> Chamber of commerce, BBB, industry associations.</li><li><strong>Get featured in local news.</strong> Did you donate to a charity? Do something noteworthy? Local papers love community stories.</li><li><strong>Create something worth linking to.</strong> A guide like "How to prepare your home for winter in New Brunswick" can attract links from other local sites.</li><li><strong>Partner with complementary businesses.</strong> You're a roofer? Partner with a real estate agent's site. They recommend you, you do the same.</li></ul><h2>What to avoid</h2><p>Don't buy thousands of cheap links from overseas. Google is incredibly good at detecting this and will penalize your site. A handful of legitimate local links will always beat a hundred spammy ones.</p><p>This is a slow game. You're not going to build 50 links in a week. But building 2 to 4 quality local links per month? After a year you'll have a backlink profile that puts you way ahead of anyone in your market.</p>`,
  },
  {
    slug: "mobile-first-website-design-why-it-matters",
    title: "Why Your Website Needs to Be Built Mobile-First",
    excerpt: "Over 60% of your visitors are on phones. If you designed for desktop and shrank it down, you're doing it backwards.",
    category: "Web Design",
    date: "June 26, 2026",
    content: `<p>Pull up your analytics or just think about your own browsing habits. Over 60% of web traffic in Canada comes from mobile devices. For local service searches like "plumber near me," it's even higher. Close to 80%.</p><p>So why are so many contractor websites clearly designed for a big desktop monitor and then awkwardly crammed onto a phone screen?</p><h2>Responsive vs. mobile-first</h2><p>Responsive means you design for desktop first, then use code to make it shrink down for phones. It usually works. Kind of. But the priorities are wrong. You end up with tiny text, buttons that are too small to tap, and layouts that force people to scroll forever.</p><p>Mobile-first means you design the phone experience first. That's your primary user. Then you expand it for larger screens. The result is a site that feels natural and fast on a phone because it was built for exactly that.</p><h2>What mobile users actually need</h2><p>Someone searching for a contractor on their phone has a problem right now. Maybe water is coming through their ceiling. Maybe their furnace just died. They need:</p><ul><li>Your phone number, tap-to-call, visible immediately</li><li>What you do, in plain language, above the fold</li><li>Where you serve</li><li>Social proof like reviews or ratings</li><li>A way to contact you without scrolling</li></ul><p>That's it. They don't need your company history. They don't need an animated hero section. They don't need parallax scrolling. They need to call you or fill out a form in under 10 seconds.</p><h2>The Google factor</h2><p>Google uses mobile-first indexing. That means Google looks at the mobile version of your site to decide how to rank you. If your mobile experience is bad, your rankings suffer even for people searching on desktop.</p><p>There's no way around this. Mobile is the default now. If your site isn't built for it from the ground up, you're leaving money on the table every single day.</p>`,
  },
